apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    environment: dev
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


# kubectl get no
# kubectl describe node kube-master | grep -i taint
# kubectl describe node kube-worker-1 | grep -i taint

# kubectl taint nodes node-name key=value:taint-effect        --- adding taint to nodes.
# kubectl taint nodes kube-worker-1 clarus=way:NoSchedule

